{
  "hash": "7e1f7c70bda59123c1c179f489cf2b98",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Filtro de Kalman Pt 2: NAIRU Bayesiana, com `bssm`\"\ndescription: \"Continuação da Parte 1 com algumas alterações. Estimação em estágio único e razão sinal-ruído λ livre em vez de calibrada, entre outras, assim como foi feito na atualização oficial do exercício no BC Blog (cuja amostra é mais longa que a da Parte 1; a minha replicação ficou mais curta, por uma limitação de dados explicada no post). Replico essa versão primeiro usando os pacotes da Parte 1 e depois com o pacote bssm, em duas versões: máxima verossimilhança e MCMC. Objetivo é contrastar as abordagens frequentista e bayesiana.\"\ndate: 2026-07-30\ncategories: [kalman filter, nairu, phillips curve, econometrics, bayesian]\ndraft: true\n---\n\n## Motivação\n\nNa [Parte 1](0001-kalman-filter-pt1-nairu.qmd) deste post, derivei o filtro de Kalman de forma simples e o usei para replicar um exercício interessante do BC Blog ([post nº29](https://www.bcb.gov.br/noticiablogbc/29/noticia) do Thiago Trafane): estimar uma NAIRU variante no tempo a partir de uma curva de Phillips de serviços. O objetivo central era ter uma aplicação prática e útil da teoria construída, e mostrar como usar essa técnica através de três pacotes diferentes de R (`MARSS`, `KFAS`, `kalmanfilter`).\n\nDepois da divulgação da Parte 1, o próprio autor do post original publicou uma atualização oficial desse exercício — o post [nº46 do BC Blog](https://www.bcb.gov.br/noticiablogbc/46/noticia), \"Inflação de serviços à luz da curva de Phillips: uma atualização\", incorporando dados mais recentes e uma reestimação metodologicamente diferente. Ela passou a ser realizada em **estágio único** (todos os parâmetros e a NAIRU estimados conjuntamente na amostra completa) e com **$\\lambda$ livre** (estimado por máxima verossimilhança, não mais calibrado em 120).\n\nEsta Parte 2 replica essa versão mais recente, primeiro rodando o exercício atualizado nos três pacotes já usados na Parte 1 (`MARSS`, `KFAS`, `kalmanfilter`) e, depois, com o pacote [`bssm`](https://cran.r-project.org/package=bssm), em **duas versões**. Uma primeira via MLE e outra via MCMC, a forma idiomática de usar o pacote. O objetivo aqui, além de atualizar as estimativas desse modelo, é também comparar duas filosofias de inferência: a frequentista e a bayesiana.\n\nEste post assume o modelo e a notação já estabelecidos no post da Parte 1. Vale a pena lê-lo primeiro se você caiu direto aqui!\n\n## Dados e setup\n\nO post original exibe uma tabela resumindo as principais atualizações entre os dois exercícios de forma clara e concisa. Reproduzo a tabela abaixo para apresentar as principais diferenças metodológicas entre os dois exercícios:\n\n![Tabela 1 do post nº46 (BCB): diferenças metodológicas entre o exercício anterior (post nº29) e o atual (post nº46).](images/kalman-filter/summary-table.png){fig-alt=\"Tabela comparando o exercício anterior e o atual em seis dimensões: amostra, medidas de inflação, estimação do parâmetro α, procedimento de estimação, variância dos termos de erro e intervalos de confiança da NAIRU.\"}\n\nEntre as mudanças mais relevantes vale destacar a extensão da amostra até os dados mais recentes disponíveis (dez/2001–mai/2026, contra dez/2001–nov/2024 na Parte 1), mudança da variável dependente que passou a ser o **núcleo EX3 de Serviços** públicado pelo BC no Sistema Gerenciador de Séries Temporais (SGS, código 29683) e a estimação em estágio único. Além disso, o autor sugere uma fonte para o desemprego retropolado utilizado. No post anterior, eu havia utilizado uma replicação minha do [Alves e Fasolo (2015)](https://www.bcb.gov.br/pec/wps/ingl/wps400.pdf) com um filtro sazonal próprio. Aqui, eu utilizo a fonte sugerida oficialmente no RPM do BCB ([Relatório de Política Monetária de junho de 2026](https://www.bcb.gov.br/noticiablogbc/46/noticia#:~:text=anexo%20estat%C3%ADstico%20do%20Relat%C3%B3rio%20de%20Pol%C3%ADtica%20Monet%C3%A1ria%20de%20junho%20de%202026%2C%20na%20aba%20Graf%201.2.11.), na aba Graf 1.2.11) — mas ela só cobre abr/2004 em diante, bem menos que a amostra completa do post nº46 (dez/2001–mai/2026).\n\nComparei essa série oficial com a minha replicação (a mesma da Parte 1, dessazonalizada via X13) nos meses em que as duas se sobrepõem e o ajuste é quase perfeito nos anos mais recentes. Por isso emendo as duas, mas só para frente, i. e., uso a série oficial de abr/2004 até onde ela vai (abr/2026) e, dali em diante, a minha própria série, até o fim da amostra disponível (mai/2026).\n\nEmendar para trás, cobrindo dez/2001–mar/2004 com a série antiga, criaria um problema diferente. As duas séries divergem em nível nesse trecho, o que geraria um degrau artificial bem no início da trajetória de $u_t^*$. Dessa forma, os resultados a seguir cobrem uma amostra mais longa do que se eu tivesse ficado só com a fonte oficial do desemprego, mas ainda mais curta que a do post nº46.\n\n> Uma última propaganda antes dos códigos! Uso o pacote [`GetBCBData`](https://github.com/msperlin/GetBCBData) do Marcelo Perlin para baixar a série de inflação. Na minha opinião, o que lida melhor com a instabilidade constante (e bem mais constante do que eu gostaria) da API do BCB para pegar a série de inflação utilizada. De resto, Focus e IPPCV continuam vindo do mesmo pipeline interno da Parte 1.\n\nComo na parte anterior, documento o *snip* de código usando minha infraestrutura de dados própria para montar a base de dados que salvo como um csv e uso no restante do exercício.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Mostrar código de coleta de dados (datalake.utils, não executado)\"}\nsuppressMessages({\n  library(here)\n  library(jsonlite)\n  library(datalake.utils)\n  library(GetBCBData)\n})\nSys.setenv(TZ = \"America/Sao_Paulo\")\n\n# IPCA -----\ndataset_id <- paste(c(c(\"latam\", \"brasil\"), \"ipca\"), collapse = \"-\")\n\nex3 <-\n  gbcbd_get_series(\n    id = 29683,\n    first.date = as.Date(\"2001-01-01\"),\n    last.date = Sys.Date()\n  )\n\nipca_ssubj <-\n  ex3 %>%\n  arrange(ref.date) %>%\n  reframe(date = ref.date, ipca_ssubj = (1 + value / 100)^12 - 1)\n\n# PNAD (desemprego dessazonalizado) -----\nu_rate <-\n  read_delim(\n    here(\"rpm0626_pnad_desemprego_monthly.csv\"),\n    delim = \";\",\n    locale = locale(encoding = \"ISO-8859-1\"),\n    show_col_types = FALSE\n  ) %>%\n  reframe(\n    date = as.Date(paste0(\"01-\", `Mês`), format = \"%d-%b-%Y\"),\n    u_rate = `Taxa de desocupação` / 100\n  )\n\nu_rate_mine <- read_csv(here(\"pnad_desemprego_retropolada.csv\")) %>%\n  reframe(\n    date,\n    u_rate = seas_dplyr(\n      u_rate,\n      year(first(date)),\n      month(first(date)),\n      12,\n      \"x13\"\n    )\n  )\n\nu_rate <-\n  u_rate %>%\n  bind_rows(filter(u_rate_mine, date > max(pull(., date))))\n\n# FOCUS (expectativas) -----\ndataset_id <- paste(c(c(\"latam\", \"brasil\"), \"focus\"), collapse = \"-\")\nfocus <-\n  read_vintage(dataset_id, table = \"db_focus_annual\") %>%\n  filter(Indicador == \"IPCA\") %>%\n  reframe(date = Data, DataReferencia, focus = Media) %>%\n  mutate(ym = as.yearmon(date)) %>%\n  group_by(ym) %>%\n  filter(date == max(date)) %>%\n  slice_max(DataReferencia, n = 1, with_ties = FALSE) %>%\n  ungroup() %>%\n  select(-ym, -DataReferencia) %>%\n  mutate(date = date %>% as.yearmon() %>% as_date())\n\n# IPPCV (índice de pressão de cadeia de suprimentos) -----\nippcv <- read_excel(here(\"ippcv.xlsx\")) %>%\n  reframe(date = as_date(`Mês`), ippcv)\n\n# Junta tudo -----\ndb_final <-\n  reduce(\n    list(ipca_ssubj, ipca_full, u_rate, focus, ippcv),\n    left_join,\n    by = \"date\"\n  ) %>%\n  mutate(ippcv = ifelse(is.na(ippcv), 0, ippcv)) %>%\n  na.trim(\"left\") %>%\n  filter(date >= \"2001-12-01\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(bssm)\nlibrary(MARSS)\nlibrary(KFAS)\nlibrary(kalmanfilter)\nlibrary(tidyverse)\nlibrary(GetBCBData)\nsource(\"R/theme_blog.R\")\n\ndb <- read_csv(\"data/kalman-filter/db_final_pt2.csv\") %>%\n  mutate(date = as_date(date))\n\ndb <- db %>%\n  arrange(date) %>%\n  mutate(\n    pi_ssubj = 100 * log1p(ipca_ssubj),\n    pi_full = 100 * log1p(ipca_full),\n    pi_full_lag1 = lag(pi_full, 1),\n    E_t = 100 * log1p(focus / 100),\n    u_t = 100 * u_rate\n  ) %>%\n  filter(!is.na(pi_full_lag1), !is.na(u_t))\n\n# Meta de inflação (CMN) por ano-calendário -- usada só na decomposição dos\n# fundamentos, mais adiante. Simplificação: usa o valor vigente no ano,\n# ignorando revisões pontuais no meio do ano.\nmetas_cmn <- GetBCBData::gbcbd_get_series(\n  id = 13521,\n  first.date = as.Date(\"2001-01-01\"),\n  last.date = Sys.Date()\n) %>%\n  reframe(year = year(ref.date), meta = value)\n\ndb <- db %>%\n  mutate(year = as.integer(format(date, \"%Y\"))) %>%\n  left_join(metas_cmn, by = \"year\")\n\nalpha <- 1.0 # reutilizado do post nº46, não recalculado\ny_v <- db$pi_ssubj - alpha - db$E_t\nc_t <- db$pi_full_lag1 - db$E_t # covariável de beta\nd_t <- -db$u_t # covariável de gamma (sinal já invertido)\nippcv_t <- db$ippcv\nn <- nrow(db)\n```\n:::\n\n\nAmostra final: May/2004–May/2026, $n=$ 265 observações mensais, mais curta que as 294 do post nº46 (dez/2001–mai/2026) pelos ~29 meses do início (dez/2001–abr/2004) que ficam de fora.\n\n## Revisitando a Parte 1: MARSS, KFAS e kalmanfilter no novo exercício\n\nAntes de entrar no [`bssm`](https://cran.r-project.org/web/packages/bssm/index.html), vale ver como ficam os três pacotes já usados na Parte 1 ([`MARSS`](https://atsa-es.github.io/MARSS/), [`KFAS`](https://cran.r-project.org/web/packages/KFAS/index.html), [`kalmanfilter`](https://cran.r-project.org/web/packages/kalmanfilter/index.html)) rodando o exercício atualizado do post nº46.\n\nAqui vale perder um tempo para explicitar as mudanças que aparecem nos códigos dos três pacotes para atender ao novo exercício.\n\nComeçando pelo `MARSS`. Intuitivamente, a Parte 2 é o 1º estágio da Parte 1 rodando na amostra toda, com uma covariável a mais e com Q, R \"soltos\". O código passa a declarar $\\beta,\\gamma,\\theta$ como parâmetros livres na matriz `D` (com as covariáveis em `d`). Sendo tudo calculado numa única etapa, todas os parâmetros são declarados de uma só vez, não precisando mais ser feito em dois passos.\n\nNa Parte 1, em vez de estimar $\\text{Var}(\\varepsilon_t)$ e $\\text{Var}(\\vartheta_t)$ como dois números livres, o código fixa `R = 1` (um valor arbitrário) e `Q = 1/λ` de forma que a razão `R/Q` seja exatamente $\\lambda=120$. Isso pode ser feito, pois a trajetória do estado estimado depende apenas da razão `R/Q`, não das variâncias individuais. Contudo, o erro-padrão do estado suavizado sai na escala errada e precisa de *rescaling*.\n\nSem a restrição do $\\lambda$, `Q`/`R` são variâncias livres e essa parte de *rescaling* não é mais necessária. A própria chamada `MARSS(..., method = \"BFGS\")` maximiza a verossimilhança dos cinco parâmetros de uma vez. O vetor `inits` ajuda a ancorar o problema, agora mais sensível ao ponto de partida.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninits_revisit <- c(beta = 0.27, gamma = 0.6, theta = 1.2, log_sd_y = log(1.6), log_sd_level = log(0.13))\n\ny_row <- matrix(y_v, nrow = 1)\nmodel_marss_1s <- list(\n  B = matrix(1),\n  U = matrix(0),\n  Q = matrix(\"q\"),\n  Z = matrix(1),\n  A = matrix(0),\n  R = matrix(\"r\"),\n  D = matrix(list(\"beta\", \"gamma\", \"theta\"), 1, 3),\n  d = rbind(c_t, d_t, ippcv_t),\n  x0 = matrix(\"x0\"),\n  V0 = matrix(1e6),\n  tinitx = 0\n)\nfit_marss <- MARSS(\n  y_row,\n  model = model_marss_1s,\n  method = \"BFGS\",\n  silent = TRUE,\n  inits = list(x0 = 0, Q = matrix(0.02), R = matrix(2), D = matrix(c(0.27, 0.6, 1.2), 1, 3)),\n  control = list(maxit = 5000, reltol = 1e-12)\n)\n\nbeta_marss <- coef(fit_marss)$D[1]\ngamma_marss <- coef(fit_marss)$D[2]\ntheta_marss <- coef(fit_marss)$D[3]\nvar_eps_marss <- coef(fit_marss)$R[1]\nvar_level_marss <- coef(fit_marss)$Q[1]\n# lambda = R/Q: gamma^2 cancela entre Var(eps_t/gamma) e a variância do estado\n# reescalado x_t = gamma*u_t* -- mesma conta da seção bssm-MLE mais abaixo.\nlambda_marss <- var_eps_marss / var_level_marss\n\nsm_marss <- tsSmooth(fit_marss, type = \"xtT\")\nnairu_marss <- tibble(\n  date = db$date,\n  pkg = \"MARSS\",\n  nairu = sm_marss$.estimate / gamma_marss,\n  se = sm_marss$.se / gamma_marss\n)\n```\n:::\n\n\nNo caso do `KFAS`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_kfas_1s <- SSModel(\n  y_v ~ -1 +\n    SSMregression(~ c_t + d_t + ippcv_t, Q = 0) +\n    SSMcustom(Z = 1, T = 1, R = 1, Q = matrix(NA), a1 = 0, P1inf = 1),\n  H = matrix(NA)\n)\n\n# inits na escala log-variância, na ordem que o updatefn padrão do fitSSM\n# espera: Q (nível) primeiro, H (observação) depois\nfit_kfas <- fitSSM(\n  model_kfas_1s,\n  inits = c(2 * inits_revisit[[\"log_sd_level\"]], 2 * inits_revisit[[\"log_sd_y\"]]),\n  method = \"BFGS\",\n  control = list(maxit = 5000, reltol = 1e-14)\n)\n\nout_kfas <- KFS(fit_kfas$model, smoothing = \"state\")\n\nbeta_kfas <- out_kfas$alphahat[nrow(out_kfas$alphahat), \"c_t\"]\ngamma_kfas <- out_kfas$alphahat[nrow(out_kfas$alphahat), \"d_t\"]\ntheta_kfas <- out_kfas$alphahat[nrow(out_kfas$alphahat), \"ippcv_t\"]\nsd_level_kfas <- unname(sqrt(exp(fit_kfas$optim.out$par[1])))\nsd_y_kfas <- unname(sqrt(exp(fit_kfas$optim.out$par[2])))\nlambda_kfas <- (sd_y_kfas / sd_level_kfas)^2\n\nnairu_kfas <- tibble(\n  date = db$date, pkg = \"KFAS\",\n  nairu = out_kfas$alphahat[, 4] / gamma_kfas,\n  se = sqrt(out_kfas$V[4, 4, ]) / gamma_kfas\n)\n```\n:::\n\n\nNO KALMANFILTER\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuild_kf_1s <- function(par) {\n  beta <- par[1]\n  gamma <- par[2]\n  theta <- par[3]\n  sd_y <- exp(par[4])\n  sd_level <- exp(par[5])\n  list(\n    B0 = matrix(0), P0 = matrix(1e6),\n    Dm = array(0, dim = c(1, 1, n)),\n    Am = array(beta * c_t + gamma * d_t + theta * ippcv_t, dim = c(1, 1, n)), # Z_t=1: estado já reescalado\n    Fm = array(1, dim = c(1, 1, n)),\n    Hm = array(1, dim = c(1, 1, n)),\n    Qm = array(sd_level^2, dim = c(1, 1, n)),\n    Rm = array(sd_y^2, dim = c(1, 1, n))\n  )\n}\nobjective_kf <- function(par) {\n  ll <- tryCatch(kalman_filter(build_kf_1s(par), matrix(y_v, nrow = 1), smooth = FALSE)$lnl, error = function(e) NA)\n  if (!is.finite(ll)) {\n    return(1e10)\n  }\n  -ll\n}\nfit_kf <- optim(\n  par = inits_revisit, fn = objective_kf, method = \"BFGS\",\n  control = list(maxit = 5000, reltol = 1e-14)\n)\n\nbeta_kf <- unname(fit_kf$par[1])\ngamma_kf <- unname(fit_kf$par[2])\ntheta_kf <- unname(fit_kf$par[3])\nsd_y_kf <- unname(exp(fit_kf$par[4]))\nsd_level_kf <- unname(exp(fit_kf$par[5]))\nlambda_kf <- (sd_y_kf / sd_level_kf)^2\n\nfilt_kf <- kalman_filter(build_kf_1s(fit_kf$par), matrix(y_v, nrow = 1), smooth = TRUE)\nnairu_kf <- tibble(\n  date = db$date, pkg = \"kalmanfilter\",\n  nairu = as.numeric(filt_kf$B_tt) / gamma_kf,\n  se = sqrt(as.numeric(filt_kf$P_tt)) / gamma_kf\n)\n```\n:::\n\n\nO IC da NAIRU aqui é o condicional simples do suavizador ($\\pm$1,96 erros-padrão, dividido por\n$\\hat\\gamma$) — o mesmo usado na Parte 1, não o bootstrap paramétrico da seção `bssm-MLE`, para\nmanter esta seção rápida. Ele portanto trata os parâmetros como conhecidos, inclusive o $\\gamma$\nque reescala o estado; e é uma banda de 95%, não diretamente comparável às de 90% das figuras do\n`bssm` mais adiante.\n\n\n::: {#tbl-coefs-revisit .cell}\n::: {.cell-output-display}\n\n\n|Pacote               |      β|      γ|      θ| ln Var(ε)|   ln λ|\n|:--------------------|------:|------:|------:|---------:|------:|\n|MARSS / kalmanfilter | 0.3402| 0.6182| 1.3487|    1.3470| 5.7821|\n|Post nº46 (BCB)      |   0.27|   0.58|   1.25|      0.97|   5.04|\n\n\n:::\n:::\n\n\n`MARSS` e `kalmanfilter` convergem para o mesmo resultado (ver abaixo) — por isso a tabela acima usa\numa única linha para os dois. O `KFAS` fica de fora dela: como o bloco de código acima já deixa ver,\nele resolve β,γ,θ por um caminho diferente (`SSMregression` + suavizador, igual à Parte 1, em vez de\num `optim()` conjunto de 5 parâmetros) e converge para um ótimo vizinho, mas não idêntico — a ressalva\ncompleta vem logo após o gráfico da NAIRU a seguir.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnairu_marss_ci <- nairu_marss %>%\n  mutate(lower = nairu - 1.96 * se, upper = nairu + 1.96 * se)\n\nggplot(nairu_marss_ci, aes(date, nairu)) +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.15, fill = pal_blog(\"main\")[1]) +\n  geom_line(color = pal_blog(\"main\")[1], linewidth = 0.7) +\n  scale_x_date_blog(nairu_marss_ci$date) +\n  labs(\n    title = \"NAIRU estimada (MARSS)\",\n    subtitle = \"% da força de trabalho, IC 95%, estágio único, λ livre\",\n    x = NULL,\n    caption = caption_blog(\"BCB\")\n  ) +\n  theme_blog()\n```\n\n::: {.cell-output-display}\n![NAIRU estimada por MARSS (KFAS e kalmanfilter chegam ao mesmo resultado -- ver tabela acima), no exercício atualizado (IC 95%, estágio único, λ livre).](0001-kalman-filter-pt2-bssm_files/figure-html/fig-nairu-revisit-1.png){#fig-nairu-revisit width=864}\n:::\n:::\n\n\n::: {.zoomable-figure}\n:::\n\nDiferente da Parte 1 — onde o `kalmanfilter` divergia visivelmente do `MARSS`/`KFAS` no 1º estágio\npor causa da parametrização direta de $\\gamma$ — aqui `MARSS` e `kalmanfilter` chegam a resultados\nnumericamente idênticos: a maior diferença entre os dois na NAIRU, em qualquer mês da amostra, fica\nabaixo de 0,0001 p.p. (por isso a figura acima mostra só o `MARSS`, como representante dos dois). Faz\nsentido: os dois maximizam a mesma verossimilhança gaussiana pelo mesmo caminho — um `optim()`\nconjunto sobre os cinco parâmetros $\\beta,\\gamma,\\theta,\\sigma_y,\\sigma_{nível}$.\n\nO `KFAS`, reescrito acima com `SSMregression`+`fitSSM()` para ficar mais parecido com a Parte 1, segue\num caminho diferente — β,γ,θ voltam a sair do suavizador via o truque do prior difuso (Parte 1), e só\n`sd_y`/`sd_level` passam por otimização externa, agora de 2 parâmetros em vez de 5 — e por isso fica\nde fora da comparação acima: converge para uma log-verossimilhança levemente melhor\n(-564.34 contra a do `optim()` conjunto de 5 parâmetros), mas com um\nλ visivelmente diferente ($\\lambda_{KFAS}\\approx$ 243 contra\n$\\lambda_{MARSS}\\approx$ 324), e uma NAIRU que chega a divergir\n0.12 p.p. da do `MARSS` no período mais\nrecente. Não é bug: é o mesmo fenômeno que a seção sobre a posterior de λ, mais abaixo, documenta\npara `bssm`-MLE vs. `bssm`-MCMC — a razão de variância λ tem verossimilhança achatada nesse modelo,\nentão duas parametrizações igualmente válidas do mesmo MLE (otimização conjunta de 5 parâmetros vs.\notimização perfilada de 2) podem pousar em pontos vizinhos, mas não idênticos, dessa crista quase\nplana.\n\nO que resta comparar, então, não é mais \"qual pacote\", mas \"qual filosofia de inferência\" — máxima\nverossimilhança vs. MCMC — que é o que o restante deste post faz, com `bssm`.\n\n## Estágio único: o que muda em relação à Parte 1\n\nA curva de Phillips estrutural é a mesma da Parte 1 — só que agora $\\theta$ entra desde o início,\njá que não há mais uma janela pré-pandemia isolada por um \"1º estágio\" com $\\theta=0$:\n\n$$\n\\pi_t^{ss} = \\alpha + \\beta\\pi_{t-1}^{12m} + (1-\\beta)E_t(\\pi^{LP}) - \\gamma(u_t-u_t^*) +\n\\theta\\,\\text{IPPCV}_t + \\varepsilon_t\n$$\n\nReparametrizando como na Parte 1 (movendo $E_t$ para o lado esquerdo, reescrevendo o estado como\n$x_t=\\gamma u_t^*$ para caber na forma `bsm_lg` do `bssm`, que fixa $Z_t=1$):\n\n$$\n\\underbrace{[\\pi_t^{ss}-\\alpha-E_t]}_{y_t} = \\beta\\underbrace{(\\pi_{t-1}^{12m}-E_t)}_{c_t} +\n\\gamma\\underbrace{(-u_t)}_{d_t} + \\theta\\,\\text{IPPCV}_t + \\underbrace{\\gamma u_t^*}_{x_t} +\n\\varepsilon_t\n$$\n\nA diferença estrutural em relação à Parte 1: $\\beta,\\gamma,\\theta$ **e** as variâncias\n$\\text{Var}(\\varepsilon_t)$, $\\text{Var}(\\vartheta_t)$ (portanto $\\lambda$) são todos estimados\njuntos, na amostra inteira — não há mais uma etapa que fixa $\\beta,\\gamma$ antes de estimar\n$\\theta$ e o estado. Isso segue o post nº46, que abandonou a separação em dois estágios (motivada\noriginalmente por isolar a pandemia dos parâmetros estruturais) em favor de máxima verossimilhança\nconjunta.\n\n## `bssm-MLE`: máxima verossimilhança, estágio único\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuild_bssm_mle <- function(par) {\n  beta <- par[1]\n  gamma <- par[2]\n  theta <- par[3]\n  sd_y <- exp(par[4]) # R = Var(eps_t)\n  sd_level <- exp(par[5]) # Q (escala do estado reescalado x_t = gamma*u_t*)\n  bsm_lg(\n    y_v,\n    sd_y = sd_y,\n    sd_level = sd_level,\n    D = beta * c_t + gamma * d_t + theta * ippcv_t,\n    a1 = 0,\n    P1 = matrix(1e6)\n  )\n}\nobjective_mle <- function(par) {\n  ll <- tryCatch(logLik(build_bssm_mle(par)), error = function(e) NA)\n  if (!is.finite(ll)) {\n    return(1e10)\n  }\n  -ll\n}\n\nfit_mle <- optim(\n  par = c(\n    beta = 0.27, gamma = 0.6, theta = 1.2,\n    log_sd_y = log(1.6), log_sd_level = log(0.13)\n  ),\n  fn = objective_mle, method = \"BFGS\", hessian = TRUE,\n  control = list(maxit = 5000, reltol = 1e-14)\n)\n\nbeta_mle <- unname(fit_mle$par[1])\ngamma_mle <- unname(fit_mle$par[2])\ntheta_mle <- unname(fit_mle$par[3])\nsd_y_mle <- unname(exp(fit_mle$par[4]))\nsd_level_mle <- unname(exp(fit_mle$par[5]))\nvar_eps_mle <- sd_y_mle^2\n# lambda = Var(eps_t/gamma)/Var(vartheta_t) = Var(eps_t)/sd_level^2 -- a\n# escala reescalada de gamma cancela no estado x_t = gamma*u_t*.\nlambda_mle <- (sd_y_mle / sd_level_mle)^2\n```\n:::\n\n\nO otimizador converge para $\\beta=$ 0.3402, $\\gamma=$ 0.6182,\n$\\theta=$ 1.3487, com $\\ln\\text{Var}(\\varepsilon_t)=$\n1.347 e $\\ln\\lambda=$ 5.7822\n($\\lambda\\approx$ 324) — mesma ordem de grandeza da Tabela 2 do post nº46\n($\\beta=0{,}27$, $\\gamma=0{,}58$, $\\theta=1{,}25$, $\\ln\\text{Var}(\\varepsilon)=0{,}97$,\n$\\ln\\lambda=5{,}04$), mas com um gap maior em $\\ln\\text{Var}(\\varepsilon)$ e $\\ln\\lambda$ do que o\nque a Parte 1 tolerava contra o post nº29. Vintage do Focus e a instabilidade de estimar duas\nvariâncias simultaneamente (em vez de calibrar $\\lambda$) ainda contribuem, como antes — mas o\nfator provavelmente dominante agora é a amostra em si: mai/2004–mai/2026 deixa de fora todo o\nperíodo inicial dos anos 2000 (desemprego estruturalmente mais alto) que entrava na estimação do\npost nº46, o que desloca o que o modelo aprende sobre o nível e a variabilidade de $u_t^*$.\n\n### Bootstrap paramétrico do IC da NAIRU\n\nO post nº46 (nota iii) constrói o intervalo de confiança da NAIRU incorporando também a incerteza\nsobre os parâmetros estimados — não só a incerteza condicional do suavizador. O procedimento:\n100 mil realizações dos parâmetros a partir de sua distribuição assintótica (normal multivariada,\nmédia = estimativa pontual, covariância = inversa da Hessiana); para cada realização, suaviza-se\no modelo e amostra-se um valor da NAIRU em cada mês; os percentis empíricos dessas 100 mil\namostras por mês aproximam a distribuição incondicional.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvcov_mle <- solve(fit_mle$hessian)\nK <- 100000\ndraws_mle <- MASS::mvrnorm(K, mu = fit_mle$par, Sigma = vcov_mle)\n\nnairu_draws <- matrix(NA_real_, nrow = K, ncol = n)\nfor (i in seq_len(K)) {\n  par_i <- draws_mle[i, ]\n  gamma_i <- par_i[2]\n  m_i <- build_bssm_mle(par_i)\n  sm_i <- smoother(m_i)\n  mean_i <- as.numeric(sm_i$alphahat[, 1])\n  sd_i <- sqrt(as.numeric(sm_i$Vt[1, 1, ]))\n  nairu_draws[i, ] <- rnorm(n, mean_i, sd_i) / gamma_i\n}\n\nmodel_final_mle <- build_bssm_mle(fit_mle$par)\nsm_mle <- smoother(model_final_mle)\nnairu_mle_point <- as.numeric(sm_mle$alphahat[, 1]) / gamma_mle\n\nqs_mle <- apply(nairu_draws, 2, quantile, probs = c(0.05, 0.95))\n\nnairu_bssm_mle <- data.frame(\n  date = db$date, pkg = \"bssm-MLE\",\n  nairu = nairu_mle_point, lower = qs_mle[1, ], upper = qs_mle[2, ]\n)\n```\n:::\n\n\n## `bssm-MCMC`: a via bayesiana nativa, estágio único\n\nComo no estágio único as variâncias $\\text{Var}(\\varepsilon_t)$ e $\\text{Var}(\\vartheta_t)$\ntambém são estimadas (não mais fixadas via $\\lambda=120$ calibrado), o `bssm-MCMC` agora precisa\nde priors sobre `sd_y` e `sd_level`, além de $\\beta,\\gamma,\\theta$. Um ponto de atenção na sintaxe\ndo `bssm`: em `normal(init, mean, sd)` e `halfnormal(init, sd)`, o argumento `init` é só o valor\ninicial do amostrador MCMC — **não** é o centro da prior. `beta = normal(c(beta_mle, gamma_mle,\ntheta_mle), 0, 1)` declara três priors $N(0,1)$ (mesma prior fracamente informativa que a Parte 2\nantiga já usava para $\\gamma$, agora estendida a $\\beta,\\theta$); `sd_y`/`sd_level` recebem\n`halfnormal(*, 5)` — meia-normal com moda em 0 e escala 5, também fracamente informativa dado que\n`sd_level` plausível fica bem abaixo de 1. `sd_y_mle`/`sd_level_mle`/`beta_mle`/`gamma_mle`/\n`theta_mle` entram só como ponto de partida do amostrador, para evitar um passeio inicial longo até\nregiões plausíveis — não como informação sobre onde a posterior deveria ficar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_mcmc <- bsm_lg(\n  y_v,\n  sd_y = halfnormal(sd_y_mle, 5),\n  sd_level = halfnormal(sd_level_mle, 5),\n  xreg = cbind(c_t, d_t, ippcv_t),\n  beta = normal(c(beta_mle, gamma_mle, theta_mle), 0, 1),\n  a1 = 0,\n  P1 = matrix(1e6)\n)\nmcmc_out <- run_mcmc(model_mcmc, iter = 20000, burnin = 4000, seed = 1)\n\ntheta_sum <- summary(mcmc_out, return_se = TRUE)\nbeta_mcmc <- theta_sum$Mean[theta_sum$variable == \"c_t\"]\ngamma_mcmc <- theta_sum$Mean[theta_sum$variable == \"d_t\"]\ntheta_mcmc <- theta_sum$Mean[theta_sum$variable == \"ippcv_t\"]\nsd_y_mcmc <- theta_sum$Mean[theta_sum$variable == \"sd_y\"]\nsd_level_mcmc <- theta_sum$Mean[theta_sum$variable == \"sd_level\"]\nlambda_mcmc <- (sd_y_mcmc / sd_level_mcmc)^2\n\n# IC da NAIRU por quantis da posterior (não aproximação normal): mcmc_out$alpha\n# inclui o estado inicial (t=0) como 1a linha -- descartada para alinhar com\n# as n datas observadas. mcmc_out$counts dá o número de repetições de cada\n# draw retido (MCMC gaussiano padrão do bssm, sem importance sampling).\ngamma_draws <- mcmc_out$theta[, \"d_t\"]\nsd_level_draws <- mcmc_out$theta[, \"sd_level\"]\nstate_draws <- mcmc_out$alpha[-1, 1, ]\nnairu_draws_mcmc <- sweep(state_draws, 2, gamma_draws, \"/\")\n\nidx_expand <- rep(seq_along(mcmc_out$counts), times = mcmc_out$counts)\nnairu_draws_mcmc_w <- nairu_draws_mcmc[, idx_expand]\n\nqs_mcmc <- apply(nairu_draws_mcmc_w, 1, quantile, probs = c(0.05, 0.95))\n\nnairu_bssm_mcmc <- data.frame(\n  date = db$date, pkg = \"bssm-MCMC\",\n  nairu = apply(nairu_draws_mcmc_w, 1, mean),\n  lower = qs_mcmc[1, ], upper = qs_mcmc[2, ]\n)\n```\n:::\n\n\n## O que a posterior de λ mostra que o MLE não mostra\n\n$\\beta,\\gamma,\\theta$ batem de perto entre `bssm-MLE` e `bssm-MCMC` (a tabela de coeficientes,\nmais abaixo, confirma). A razão sinal-ruído $\\lambda$, porém, diverge de verdade — e é sobre essa\ndivergência que vale focar, já que é a primeira vez nesta série de posts em que os dois métodos\nnão concordam essencialmente até a última casa decimal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_x <- seq(0, max(sd_level_draws) * 1.1, length.out = 400)\nprior_df <- data.frame(\n  x = prior_x,\n  density = 2 * dnorm(prior_x, 0, 5)\n)\n\nggplot() +\n  geom_histogram(\n    aes(x = sd_level_draws, y = after_stat(density)),\n    bins = 60, fill = pal_blog(\"main\")[1], alpha = 0.55, color = NA\n  ) +\n  geom_line(data = prior_df, aes(x, density), color = accent_blog(), linewidth = 0.8) +\n  geom_vline(xintercept = sd_level_mle, linetype = \"dashed\", color = pal_blog(\"main\")[1]) +\n  geom_vline(xintercept = sd_level_mcmc, linetype = \"dotted\", color = accent_blog()) +\n  labs(\n    title = \"Posterior de sd_level (bssm-MCMC)\",\n    subtitle = \"Densidade estimada via MCMC, vs. prior halfnormal(0, 5) declarada\",\n    x = \"sd_level\",\n    caption = caption_blog(\"BCB\")\n  ) +\n  theme_blog()\n```\n\n::: {.cell-output-display}\n![Posterior de sd_level (estágio único, bssm-MCMC) vs. a prior halfnormal(0, 5) declarada.](0001-kalman-filter-pt2-bssm_files/figure-html/fig-posterior-sdlevel-1.png){#fig-posterior-sdlevel width=864}\n:::\n:::\n\n\nA prior (linha laranja) é uma meia-normal com moda em 0 — quase plana no intervalo relevante\n(escala 5 é grande frente à faixa plausível de `sd_level`, entre 0 e ~1). A posterior (histograma)\nestá muito longe dessa moda: concentrada entre aproximadamente 0,1 e 0,3, com média em\n0.1711 (linha pontilhada laranja) — bem deslocada do ponto de máxima\nverossimilhança, `sd_level_mle` = 0.1089 (linha tracejada verde). Com uma\nprior fracamente informativa (não centrada em nenhum dos dois candidatos), os dados dominam a\nprior como já acontecia com $\\gamma$ na Parte 2 antiga — só que agora o que a posterior \"decide\"\nsobre esse parâmetro diverge visivelmente do que o otimizador BFGS decidiu, o que não acontecia\nantes. Um `sd_level` maior implica um $\\lambda$ menor: a posterior MCMC deixa a NAIRU se mover mais\nmês a mês do que o ótimo pontual do MLE sugere ($\\lambda_{MLE}\\approx$ 324\nvs. $\\lambda_{MCMC}\\approx$ 131).\n\n### O MCMC precisa convergir — o MLE não\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrace_df <- data.frame(iter = seq_along(sd_level_draws), sd_level = sd_level_draws)\n\nggplot(trace_df, aes(iter, sd_level)) +\n  geom_line(color = pal_blog(\"main\")[1], linewidth = 0.25, alpha = 0.8) +\n  labs(\n    title = \"Traceplot da cadeia de sd_level\",\n    subtitle = \"Estágio único, pós burn-in\",\n    x = \"Iteração\",\n    caption = caption_blog(\"BCB\")\n  ) +\n  theme_blog()\n```\n\n::: {.cell-output-display}\n![Traceplot da cadeia de sd_level -- mistura em torno da posterior, sem tendência visível.](0001-kalman-filter-pt2-bssm_files/figure-html/fig-mcmc-diagnostics-1.png){#fig-mcmc-diagnostics width=864}\n:::\n:::\n\n\n\n::: {#tbl-ess .cell}\n\n```{.r .cell-code}\nkable(\n  theta_sum[, c(\"variable\", \"Mean\", \"SD\", \"ESS\")],\n  col.names = c(\"Parâmetro\", \"Média posterior\", \"DP\", \"ESS\"),\n  digits = 4\n)\n```\n\n::: {.cell-output-display}\n\n\n|Parâmetro | Média posterior|     DP| ESS|\n|:---------|---------------:|------:|---:|\n|c_t       |          0.3508| 0.1036| 880|\n|d_t       |          0.6101| 0.1187| 627|\n|ippcv_t   |          1.2399| 0.3185| 812|\n|sd_level  |          0.1711| 0.0786| 728|\n|sd_y      |          1.9584| 0.0917| 817|\n\n\n:::\n:::\n\n\nO **ESS** (*effective sample size*) resume quantas das 16000\niterações pós burn-in valem como amostras efetivamente independentes, dada a autocorrelação da\ncadeia. `d_t` ($\\gamma$) tem o menor ESS dos cinco parâmetros, seguido de perto por `sd_level`. Não\né só uma questão do amostrador partir longe da posterior: `gamma_mle` já está bem perto da média\nposterior de $\\gamma$ (tabela acima), então a distância até o ponto de partida sozinha não explica\num ESS baixo aqui. Uma explicação mais estrutural: $\\gamma$ entra na equação de observação **e**\nreescala o estado latente a cada iteração ($x_t=\\gamma u_t^*$), o que tende a gerar mais\nautocorrelação na cadeia por acoplamento entre parâmetro e estado — um problema clássico de\namostragem em modelos de espaço de estados. Nada disso tem equivalente no MLE: o otimizador BFGS é\ndeterminístico e não precisa de diagnóstico de convergência — resolve um problema de otimização, não\nde amostragem.\n\n## Resultados\n\n### Coeficientes\n\n\n::: {#tbl-coefs .cell}\n\n```{.r .cell-code}\ntbl_coefs <- data.frame(\n  Pacote = c(\"bssm-MLE\", \"bssm-MCMC\", \"Post nº46 (BCB)\"),\n  beta = c(\n    sprintf(\"%.4f\", beta_mle), sprintf(\"%.4f\", beta_mcmc), \"0.27\"\n  ),\n  gamma = c(\n    sprintf(\"%.4f\", gamma_mle), sprintf(\"%.4f\", gamma_mcmc), \"0.58\"\n  ),\n  theta = c(\n    sprintf(\"%.4f\", theta_mle), sprintf(\"%.4f\", theta_mcmc), \"1.25\"\n  ),\n  ln_var_eps = c(\n    sprintf(\"%.4f\", log(var_eps_mle)), sprintf(\"%.4f\", log(sd_y_mcmc^2)), \"0.97\"\n  ),\n  ln_lambda = c(\n    sprintf(\"%.4f\", log(lambda_mle)), sprintf(\"%.4f\", log(lambda_mcmc)), \"5.04\"\n  )\n)\nkable(\n  tbl_coefs,\n  col.names = c(\"Pacote\", \"β\", \"γ\", \"θ\", \"ln Var(ε)\", \"ln λ\"),\n  align = c(\"l\", \"r\", \"r\", \"r\", \"r\", \"r\")\n)\n```\n\n::: {.cell-output-display}\n\n\n|Pacote          |      β|      γ|      θ| ln Var(ε)|   ln λ|\n|:---------------|------:|------:|------:|---------:|------:|\n|bssm-MLE        | 0.3402| 0.6182| 1.3487|    1.3470| 5.7822|\n|bssm-MCMC       | 0.3508| 0.6101| 1.2399|    1.3442| 4.8757|\n|Post nº46 (BCB) |   0.27|   0.58|   1.25|      0.97|   5.04|\n\n\n:::\n:::\n\n\n$\\beta,\\gamma,\\theta$ concordam de perto entre `bssm-MLE` e `bssm-MCMC` — coeficientes ligados\ndiretamente à verossimilhança das 265 observações mensais, com estrutura de regressão\nrelativamente simples. `ln Var(ε)` também concorda razoavelmente. `ln λ`, porém, é onde os dois\nmétodos discordam de verdade (seção acima) — um lembrete de que razões de variância em modelos de\nespaço de estados são notoriamente mais difíceis de identificar que coeficientes de regressão: a\nverossimilhança em função de $\\lambda$ tende a ser mais achatada, e o ponto de máximo (MLE) não é\nnecessariamente representativo de onde está a maior parte da massa posterior.\n\n### A trajetória da NAIRU\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnairu_all <- bind_rows(nairu_bssm_mle, nairu_bssm_mcmc)\n\nggplot(nairu_all, aes(date, nairu, color = pkg, fill = pkg)) +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.15, color = NA) +\n  geom_line(linewidth = 0.7) +\n  scale_color_blog(tier = \"contrast\") +\n  scale_fill_blog(tier = \"contrast\") +\n  scale_x_date_blog(nairu_all$date) +\n  labs(\n    title = \"NAIRU estimada por bssm-MLE e bssm-MCMC\",\n    subtitle = \"% da força de trabalho, IC 90%, estágio único\",\n    x = NULL,\n    caption = caption_blog(\"BCB\")\n  ) +\n  theme_blog()\n```\n\n::: {.cell-output-display}\n![NAIRU estimada (com IC 90%), pelas duas vias -- MLE (bootstrap paramétrico) e MCMC (quantis da posterior).](0001-kalman-filter-pt2-bssm_files/figure-html/fig-nairu-bssm-1.png){#fig-nairu-bssm width=864}\n:::\n:::\n\n\n::: {.zoomable-figure}\n:::\n\nAs duas faixas se sobrepõem na maior parte da amostra, mas divergem visivelmente onde o\n$\\lambda$ menor do MCMC (posterior mais permissiva com movimento mês a mês) permite que a NAIRU\ncapture mais variação de curto prazo que o MLE suaviza para fora — mais perceptível no pico de\n2008–2011 e, num grau menor, perto do fim da amostra. A banda do MCMC também é sistematicamente mais\nlarga, mesma lógica: menos suavização implica mais incerteza sobre onde exatamente o estado está em\ncada mês.\n\n### O hiato do desemprego hoje\n\n\n::: {.cell}\n\n```{.r .cell-code}\nultima_data <- max(db$date)\nu_hoje <- tail(db$u_t, 1)\nnairu_hoje_mle <- tail(nairu_bssm_mle$nairu, 1)\nnairu_hoje_mle_lo <- tail(nairu_bssm_mle$lower, 1)\nnairu_hoje_mle_hi <- tail(nairu_bssm_mle$upper, 1)\nhiato_hoje <- u_hoje - nairu_hoje_mle\n```\n:::\n\n\nNesta replicação (`bssm-MLE`), o desemprego observado em May/2026\n(5.41%) está 2.08 p.p. **abaixo** da NAIRU estimada\n(7.5%, IC 90% [6.09%,\n8.91%]) — mercado de trabalho aquecido, mesmo sinal qualitativo do post\nnº46. O post oficial reporta números um pouco diferentes para o mesmo mês-base (desemprego 5,4%,\nNAIRU 7,2%, hiato -1,8 p.p., IC 95% inteiramente acima do desemprego): mesmo com o núcleo EX3\nServiços e o desemprego agora vindo essencialmente da mesma fonte oficial que o BCB usa — o último\nmês da amostra, mai/2026, vem da minha própria série emendada, não da RPM (seção acima) —, Focus e\nIPPCV ainda vêm do pipeline interno da Parte 1, e a amostra de estimação aqui é bem mais curta\n(mai/2004–mai/2026 contra dez/2001–mai/2026 no post nº46), o que pesa sobre o nível estimado da\nNAIRU (seção anterior). O sinal do hiato — mercado aquecido — se confirma; a magnitude diverge um\npouco mais do que a Parte 1 divergia do post nº29.\n\n## Decomposição dos fundamentos do núcleo EX3 Serviços\n\nNovidade do post nº46 sem equivalente na Parte 1: reescrever a curva de Phillips em relação a uma\n**meta ajustada** ($\\bar\\pi_t+\\alpha$, em que $\\bar\\pi_t$ é a meta de inflação vigente no mês) e\ndecompor o desvio da inflação observada em relação a ela em cinco componentes:\n\n$$\n\\pi_t^{ss}-(\\bar\\pi_t+\\alpha) = \\underbrace{\\beta(\\pi_{t-1}^{12m}-\\bar\\pi_t)}_{\\text{i. inflação passada}}\n+ \\underbrace{(1-\\beta)(E_t(\\pi^{LP})-\\bar\\pi_t)}_{\\text{ii. expectativas}}\n\\underbrace{-\\gamma(u_t-u_t^*)}_{\\text{iii. hiato do desemprego}}\n+ \\underbrace{\\theta\\,\\text{IPPCV}_t}_{\\text{iv. pandemia}}\n+ \\underbrace{\\varepsilon_t}_{\\text{v. erro}}\n$$\n\nOs quatro primeiros componentes somados formam o **fundamento** do núcleo EX3 Serviços — a parte\n\"explicada pelo modelo\", mais suave que a série observada (que ainda carrega o ruído $\\varepsilon_t$).\nSigo o post nº46 e trato (iii) e (iv) em conjunto: não dá para separar de forma limpa quanto do\nefeito da pandemia foi sobre a própria NAIRU vs. sobre um choque transitório da curva de Phillips\ncapturado por $\\text{IPPCV}_t$. Uso as estimativas pontuais do `bssm-MLE` (não do MCMC) para uma\ndecomposição de ponto único, sem propagar incerteza.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecomp_monthly <- db %>%\n  mutate(\n    nairu = nairu_mle_point,\n    meta_ajustada = meta + alpha,\n    observado = pi_ssubj - meta_ajustada,\n    inflacao_passada = beta_mle * (pi_full_lag1 - meta),\n    expectativas = (1 - beta_mle) * (E_t - meta),\n    hiato_ippcv = -gamma_mle * (u_t - nairu) + theta_mle * ippcv,\n    fundamento = inflacao_passada + expectativas + hiato_ippcv\n  )\n\n# Média móvel de 12 meses (equivalente ao \"Gráfico 2\" do post nº46).\ndecomp_12m <- decomp_monthly %>%\n  arrange(date) %>%\n  mutate(\n    across(\n      c(observado, inflacao_passada, expectativas, hiato_ippcv, fundamento),\n      ~ zoo::rollmeanr(.x, k = 12, fill = NA)\n    )\n  ) %>%\n  filter(!is.na(fundamento))\n\ndecomp_long <- decomp_12m %>%\n  select(date, inflacao_passada, expectativas, hiato_ippcv) %>%\n  tidyr::pivot_longer(-date, names_to = \"componente\", values_to = \"valor\") %>%\n  mutate(\n    componente = factor(\n      componente,\n      levels = c(\"hiato_ippcv\", \"expectativas\", \"inflacao_passada\"),\n      labels = c(\n        \"Hiato do desemprego + IPPCV\",\n        \"Expectativa de inflação - meta\",\n        \"Inflação passada - meta\"\n      )\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_col(data = decomp_long, aes(date, valor, fill = componente), position = \"stack\") +\n  geom_line(\n    data = decomp_12m,\n    aes(date, fundamento, color = \"Fundamento EX3 Serviços - meta ajustada\"),\n    linewidth = 0.8\n  ) +\n  geom_line(\n    data = decomp_12m,\n    aes(date, observado, color = \"EX3 Serviços - meta ajustada\"),\n    linewidth = 0.8\n  ) +\n  scale_fill_blog(tier = \"extended\", n = 3) +\n  scale_color_manual(\n    values = c(\n      \"Fundamento EX3 Serviços - meta ajustada\" = accent_blog(\"cool\"),\n      \"EX3 Serviços - meta ajustada\" = accent_blog(\"warm\")\n    )\n  ) +\n  scale_x_date_blog(decomp_12m$date) +\n  labs(\n    title = \"Decomposição da inflação do núcleo EX3 Serviços\",\n    subtitle = \"p.p. em relação à meta ajustada, acumulado 12m\",\n    x = NULL,\n    caption = caption_blog(\"BCB\")\n  ) +\n  theme_blog()\n```\n\n::: {.cell-output-display}\n![Decomposição da inflação do núcleo EX3 Serviços em relação à meta ajustada (bssm-MLE), acumulado em 12 meses.](0001-kalman-filter-pt2-bssm_files/figure-html/fig-decomp-1.png){#fig-decomp width=864}\n:::\n:::\n\n\n::: {.zoomable-figure}\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nultimo_decomp <- tail(decomp_12m, 1)\n```\n:::\n\n\nNo último mês da decomposição (May/2026, acumulado 12m), o\nfundamento está em 2.1 p.p. acima da meta ajustada, dos quais\n1.21 p.p. vêm do hiato do desemprego (+IPPCV) e\n0.9 p.p. de inflação passada\ne expectativas combinadas — mesma leitura qualitativa do post nº46: aproximadamente metade do\ndesvio vem de mercado de trabalho aquecido, a outra metade de inflação passada e esperada acima da\nmeta.\n\n## Frequentista vs. bayesiano: onde concordam, onde divergem\n\n**MLE**: trata $\\beta,\\gamma,\\theta$ e as variâncias como números fixos desconhecidos, estima um\núnico ponto ótimo, e agora — diferente da Parte 1 — incorpora a incerteza sobre os próprios\nparâmetros no IC da NAIRU via bootstrap paramétrico (100 mil draws da normal assintótica em torno\ndo ótimo). Essa é uma melhoria real em relação ao desenho de dois estágios da Parte 1, onde\n$\\beta,\\gamma$ eram simplesmente \"plugados\" como fixos no 2º estágio, sem propagar sua própria\nincerteza.\n\n**MCMC**: trata todos os parâmetros como variáveis aleatórias, combina priors (aqui, fracamente\ninformativas — $N(0,1)$ para $\\beta,\\gamma,\\theta$, meia-normal(0, escala 5) para as variâncias,\nnenhuma delas centrada no MLE) com a verossimilhança dos dados, e devolve a distribuição\n*a posteriori* inteira. O IC por quantis da posterior reflete diretamente essa distribuição — sem\ndepender de uma aproximação normal em torno de um único ponto.\n\nO que os resultados acima mostram é que essas duas formas de propagar incerteza **concordam bem**\npara $\\beta,\\gamma,\\theta$ — parâmetros de regressão diretamente informados por 265 observações\nmensais — mas **divergem** para $\\lambda$: uma razão de variâncias, notoriamente mal identificada\nem modelos de espaço de estados, onde a curvatura local da verossimilhança (que o bootstrap do\nMLE usa) pode não representar bem o formato real — possivelmente assimétrico — da distribuição\ncompleta que o MCMC amostra. Não é um resultado geral de que \"MCMC é sempre mais confiável para\nvariâncias\" — é uma consequência concreta e visível neste modelo específico, com essa amostra:\no bootstrap aproxima a posterior por uma normal centrada no MLE, e essa aproximação vai bem para\nalguns parâmetros e mal para outros. Saber diferenciar os dois casos — sem rodar as duas\nabordagens lado a lado — não é trivial; é exatamente por isso que vale a pena comparar.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}